Chore/ci setup
LedgerSync/ledger_sync-template_ledger pull request #1
Opened 2021-02-17 02:20 UTC by amouxkin

Why
- To add git hub actions to the workflow: runocop, rspec and publish

How
- created a yaml config file

2021-02-17 02:21 UTC, amouxkin commented
For Actual workflow to be completed "RUBY_GEM_KEY" must be defined as a secret.

2021-02-17 10:18 UTC, ryanwjackson requested changes

2021-02-17 10:18 UTC, ryanwjackson commented on README.md
> +7. Create a `RUBY_GEM_KEY` secret for publishing the GEM.
This belongs in the repo, right? Can we add more specific instructions for how to put this key in the repo?

2021-02-19 13:49 UTC, ryanwjackson approved these changes

2021-02-19 13:49 UTC, merged